# Dockerfile.django
FROM python:3.11-slim

# Set working directory
WORKDIR /app


# Copy backend code
COPY backend/ /app/

# Install Python dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Expose port
EXPOSE 8000

# Collect static files (optional, if used)
# RUN python manage.py collectstatic --noinput

# Run Django server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
