version: '3.9'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    volumes:
      - ./backend/:/app/
    ports:
      - "8000:8000"
    env_file:
      - ./config/.env
    depends_on:
      - db

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    volumes:
      - ./fastapi_service/:/app/
    ports:
      - "8001:8001"
    env_file:
      - ./config/.env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: vacationdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
