# Dockerfile.fastapi
FROM python:3.11-slim

WORKDIR /app

COPY fastapi_service/ /app/

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8001

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
