# Generated by Django 5.2 on 2025-05-04 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleId', models.AutoField(primary_key=True, serialize=False)),
                ('roleName', models.CharField(max_length=100, unique=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobileNo', models.CharField(max_length=15)),
                ('loginTime', models.DateTimeField(blank=True, null=True)),
                ('logoutTime', models.DateTimeField(blank=True, null=True)),
                ('isLogin', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('roleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacationApp.role')),
            ],
        ),
    ]
