# Generated by Django 5.2 on 2025-05-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacationApp', '0002_rename_roleid_user_role_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobileNo',
            field=models.CharField(max_length=14),
        ),
    ]
