# Generated by Django 5.2 on 2025-05-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacationApp', '0003_alter_user_mobileno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobileNo',
            field=models.CharField(max_length=15),
        ),
    ]
